safe: true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: https://www.jhipster.tech
github_repository_url: https://github.com/jhipster/jhipster.github.io
kramdown:
  input: GFM
plugins:
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-redirect-from
  - jemoji
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
